window.$ = window.jQuery = require('jquery');
require('./file/popper.min.js');
require('./file/bootstrap.min.js');
require('@fortawesome/fontawesome-free/js/all.min.js');
require("sweetalert2");
require('./file/admin/app.min.js');
require('./file/admin/app.init.js');
require('./file/admin/perfect-scrollbar.jquery.min.js');
require('./file/admin/sparkline.js');
require('./file/admin/waves.js');
require('./file/admin/sidebarmenu.js');
require('./file/admin/jquery.tagsinput-revisited.js');
window.ClassicEditor = require('@ckeditor/ckeditor5-build-classic');
require('./file/admin/custom.js');
